format = """
[ î‚¶](#4c566a)\
$os\
[î‚°](bg:#2e3440 fg:#4c566a)\
[î‚°](bg:#4c566a fg:#2e3440)\
[î‚°](bg:#2e3440 fg:#4c566a)\
[î‚°](bg:#4c566a fg:#2e3440)\
[î‚° ](bg:#2e3440 fg:#4c566a)\
$username\
[î‚°](bg:#4c566a fg:#2e3440)\
$directory\
[î‚°](bg:#3b4252 fg:#4c566a)\
$git_branch\
$git_status\
[î‚°](fg:#3b4252 bg:#2e3440)\
[î‚°](fg:#2e3440 bg:#4c566a)\
$cmd_duration\
[î‚°](fg:#4c566a bg:#434c5e)\
$c\
$cpp\
$golang\
$haskell\
$java\
$nodejs\
$python\
$rust\
[î‚°](bg:#3b4252 fg:#434c5e)\
$time\
[î‚° ](fg:#3b4252)\
"""

# A new line at the beginning


add_newline = true

[username]
show_always = true
style_user = "bg:#2e3440 fg:#ffffff"
style_root = "bg:#2e3440"
format = '[lvrzrock ]($style)'
disabled = false

# Display OS
[os]
style = "bg:#4c566a"
disabled = false # Disabled by default

# Supported OS Symbols in this prompt
[os.symbols]
AlmaLinux = "ïŒ"
Alpine = "ïŒ€"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ïŒŸ"
CachyOS = "î±"
CentOS = "î¼½"
Debian = "î½"
DragonFly = "î»¸"
EndeavourOS = "ïŒ¢ "
Fedora = "îŸ™"
FreeBSD = "ïŠ"
Garuda = "ïŒ·"
Gentoo = "îŸ¦"
Kali = "ïŒ§"
Linux = "ï…¼"
Macos = "îœ‘"
Manjaro = "ïŒ’"
Mint = "ó°£­"
NetBSD = "ğŸš© "
NixOS = "ó±„…"
Nobara = "ï€"
OpenBSD = "ïŒ¨"
openSUSE = "î¡—"
OracleLinux = "ó°«¼"
Pop = "ïŒª"
Raspbian = "îœ¢"
Redhat = "î½"
RedHatEnterprise = "î½"
RockyLinux = "î¢‘"
Solus = "ïŒ­"
SUSE = "î½­"
Ubuntu = "î½²"
Unknown = "î¯ƒ"
Void = "ïŒ®"
Windows = "î˜ª"

[directory]
style = "bg:#4c566a fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#3b4252 fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3b4252 fg:#000000"
format = '[$all_status$ahead_behind ]($style)'


[time]
disabled = false
time_format = "%b %d, %I:%M %P" # Hour:Minute Format
style = "bg:#3b4252 fg:#ffffff"
format = "[ $time ]($style)"

[cmd_duration]
disabled = false
min_time = 2000
style = 'bg:#4c566a fg:#000000'
format = '[ Took $duration!]($style)'

[c]
symbol = "C "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version(-$name) )]($style)'
disabled = false

[cpp]
symbol = "î™† "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version(-$name) )]($style)'
disabled = false

[golang]
symbol = "î "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[haskell]
symbol = "ó°²’ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[java]
symbol = "îœ¸ "
style = "bg:#434c5e fg:#ffffff"
format = '[ ${symbol}(${version} )]($style)'
disabled = true

[nodejs]
symbol = "îµ„ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[rust]
symbol = "î¨ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[python]
symbol = "îœ¼ "
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bg:#434c5e fg:#ffffff"
disabled = true
